### ISSUE TITLE
Elementor plugin is displaying an error during the runtime check

### ISSUE THREAD

**Issue by mukeshpanchal27** [10up/plugin-check#185]
### Describe the bug

During our runtime checks for plugins, we discovered that if the Elementor plugin is active on a website, it also triggers an error. To ensure a smooth experience for other plugins, it is essential that we address this issue promptly.

### Steps to Reproduce

1. Take latest pull from the branch.
2. Set up a WordPress environment.
3. Install and activate the Elementor plugin.
4. Navigate to the `Admin Panel > Tools > Plugin Check`.
5. Select Elementor from the dropdown menu and click the "Check it!" button.
6. Perform the check for a second time.
7. Check for any errors in your `debug.log` file.

### Screenshots, screen recording, code snippet

```
PHP Fatal error:  Uncaught Exception: Invalid post. in /var/www/html/wp-content/plugins/elementor/core/settings/page/manager.php:101
Stack trace:
#0 /var/www/html/wp-content/plugins/elementor/core/base/document.php(1688): Elementor\Core\Settings\Page\Manager->ajax_before_save_settings(Array, NULL)
#1 /var/www/html/wp-content/plugins/elementor/core/base/document.php(801): Elementor\Core\Base\Document->save_settings(Array)
#2 /var/www/html/wp-content/plugins/elementor/core/kits/manager.php(295): Elementor\Core\Base\Document->update_settings(Array)
#3 /var/www/html/wp-content/plugins/elementor/core/kits/manager.php(457): Elementor\Core\Kits\Manager->update_kit_settings_based_on_option('site_name', 'Plugin Check')
#4 /var/www/html/wp-includes/class-wp-hook.php(310): Elementor\Core\Kits\Manager->Elementor\Core\Kits\{closure}('My Site', 'Plugin Check')
#5 /var/www/html/wp-includes/class-wp-hook.php(332): WP_Hook->apply_filters('', Array)
#6 /var/www/html/wp-includes/plugin.php(517): WP_Hook->do_action(Array)
#7 /var/www/html/wp-includes/option.php(570): do_action('update_option_b...', 'My Site', 'Plugin Check', 'blogname')
#8 /var/www/html/wp-admin/includes/upgrade.php(58): update_option('blogname', 'Plugin Check')
#9 /var/www/html/wp-content/plugins/plugin-check/includes/Checker/Runtime_Environment_Setup.php(39): wp_install('Plugin Check', 'plugincheck', 'demo@pluginchec...', false)
#10 /var/www/html/wp-content/plugins/plugin-check/includes/CLI/Plugin_Check_Command.php(136): WordPress\Plugin_Check\Checker\Runtime_Environment_Setup->set_up()
#11 [internal function]: WordPress\Plugin_Check\CLI\Plugin_Check_Command->check(Array, Array)
#12 phar:///usr/local/bin/wp/vendor/wp-cli/wp-cli/php/WP_CLI/Dispatcher/CommandFactory.php(100): call_user_func(Array, Array, Array)
#13 [internal function]: WP_CLI\Dispatcher\CommandFactory::WP_CLI\Dispatcher\{closure}(Array, Array)
#14 phar:///usr/local/bin/wp/vendor/wp-cli/wp-cli/php/WP_CLI/Dispatcher/Subcommand.php(491): call_user_func(Object(Closure), Array, Array)
#15 phar:///usr/local/bin/wp/vendor/wp-cli/wp-cli/php/WP_CLI/Runner.php(419): WP_CLI\Dispatcher\Subcommand->invoke(Array, Array, Array)
#16 phar:///usr/local/bin/wp/vendor/wp-cli/wp-cli/php/WP_CLI/Runner.php(442): WP_CLI\Runner->run_command(Array, Array)
#17 phar:///usr/local/bin/wp/vendor/wp-cli/wp-cli/php/WP_CLI/Runner.php(1256): WP_CLI\Runner->run_command_and_exit()
#18 phar:///usr/local/bin/wp/vendor/wp-cli/wp-cli/php/WP_CLI/Bootstrap/LaunchRunner.php(28): WP_CLI\Runner->start()
#19 phar:///usr/local/bin/wp/vendor/wp-cli/wp-cli/php/bootstrap.php(78): WP_CLI\Bootstrap\LaunchRunner->process(Object(WP_CLI\Bootstrap\BootstrapState))
#20 phar:///usr/local/bin/wp/vendor/wp-cli/wp-cli/php/wp-cli.php(32): WP_CLI\bootstrap()
#21 phar:///usr/local/bin/wp/php/boot-phar.php(11): include('phar:///usr/loc...')
#22 /usr/local/bin/wp(4): include('phar:///usr/loc...')
#23 {main}
  thrown in /var/www/html/wp-content/plugins/elementor/core/settings/page/manager.php on line 101
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by swissspidy** [comment]
is this still happening?

**Comment by swissspidy** [comment]
Can't reproduce

**Comment by mukeshpanchal27** [comment]
@swissspidy sorry for late reply. I still reproduce the issue with Elementor plugin when it activated.

See video: https://drive.google.com/file/d/1fuL5xpyZJQPVn3WZkrxKOjafFQWUXmp0/view?usp=sharing
